name: flutter_meta_sdk
description: Meta SDK for Flutter. This package allow you to integration with Facebook SDK using developer facebook dashboard, track flutter app events, and etc.
version: 1.1.0
homepage: https://github.com/chandrabezzo/flutter_meta_sdk

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.solusibejo.flutter_meta_sdk
        pluginClass: FlutterMetaSdkPlugin
      ios:
        pluginClass: FlutterMetaSdkPlugin
      web:
        pluginClass: FlutterMetaSdkWeb
        fileName: flutter_meta_sdk_web.dart

